---
- name: Install sshpass
  ansible.builtin.yum:
    name: sshpass
    state: present

- name: Copy admin.conf to remote host
  ansible.builtin.shell:
    cmd: sshpass -p "{{ remote_password }}" scp /etc/kubernetes/admin.conf root@{{ infra_ip }}:/root/