---
# Install Kubernetes and CRI-O
- name: Add Kubernetes YUM repository
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key

- name: Add CRI-O YUM repository
  copy:
    dest: /etc/yum.repos.d/cri-o.repo
    content: |
      [cri-o]
      name=CRI-O
      baseurl=https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/rpm/repodata/repomd.xml.key

- name: Search for required packages (debug)
  command: dnf search kubectl kubeadm kubelet cri-o
  register: package_search
  changed_when: false
  ignore_errors: true

- name: Install required packages
  dnf:
    name:
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable and start CRI-O and Kubelet services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - crio.service
    - kubelet

- name: Disable and stop Firewalld
  systemd:
    name: firewalld
    enabled: false
    state: stopped

- name: Set SELinux to permissive
  selinux:
    state: permissive

- name: Disable Swap
  shell: |
    swapoff -a
    sed -i 's/\/dev\/mapper\/rl-swap/\#\/dev\/mapper\/rl-swap/g' /etc/fstab
    systemctl daemon-reload
  register: swapoff_output

- name: Configure sysctl for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s-mod.conf
    content: |
      net.bridge.bridge-nf-call-iptables=1
      net.ipv4.ip_forward=1
      net.bridge.bridge-nf-call-ip6tables=1

- name: Reload sysctl settings
  command: sysctl --system

- name: Load required kernel modules
  copy:
    dest: /etc/modules-load.d/k8s-modules.conf
    content: |
      br_netfilter
      overlay

- name: Load kernel modules immediately
  shell: |
    modprobe br_netfilter
    modprobe overlay

- name: Update /etc/hosts file
  copy:
    dest: /etc/hosts
    content: |
      192.168.10.10 node1.example.com node1
      192.168.10.20 node2.example.com node2
      192.168.10.30 node3.example.com node3
      192.168.10.100 storage.example.com storage