# roles/configure_network/tasks/main.yml
---
- name: Configure IPv4 address for the network connection
  ansible.builtin.command:
    cmd: "nmcli connection modify '{{ network_connection_name }}' ipv4.addresses '{{ ipv4_address }}'"

- name: Configure IPv4 method for the network connection
  ansible.builtin.command:
    cmd: "nmcli connection modify '{{ network_connection_name }}' ipv4.method '{{ ipv4_method }}'"

- name: Restart NetworkManager service using nmcli
  ansible.builtin.command:
    cmd: nmcli networking off && nmcli networking on
  become: yes
  register: network_restart

- name: Check if NetworkManager restarted successfully
  debug:
    var: network_restart