# This is a clouds.yaml file, which can be used by OpenStack tools as a source
# of configuration on how to connect to a cloud. If this is your only cloud,
# just put this file in ~/.config/openstack/clouds.yaml and tools like
# python-openstackclient will just work with no further config. (You will need
# to add your password to the auth section)
# If you have more than one cloud account, add the cloud entry to the clouds
# section of your existing file and you can refer to them by name with
# OS_CLOUD=openstack or --os-cloud=openstack
clouds:
  openstack:
    auth:
      auth_url: https://vlab.dustbox.kr:5000
      username: "user3"
      project_id: 3937c9878ce444dfba2a26f3c2752dc6
      project_name: "user3"
      user_domain_name: "student"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3