all:
  children:
    k8s-controller:
      hosts:
        root:
          ansible_host: 10.0.0.194
    k8s-compute1:
      hosts:
        root:
          ansible_host: 10.0.0.2
    k8s-compute2:
      hosts:
        root:
          ansible_host: 10.0.0.112
    k8s-infra:
      hosts:
        root:
          ansible_host: 10.0.0.98