---
- name: Ensure .kube directory exists
  file:
    path: "{{ kube_config_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Copy admin.conf to .kube/config
  copy:
    src: "/root/admin.conf"
    dest: "{{ kube_config_dir }}/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Export KUBECONFIG environment variable
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export KUBECONFIG={{ kube_config_dir }}/config"
    state: present
    
- name: Ensure kubeconfig environment variable is set for the current user
  lineinfile:
    path: ~/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    state: present

- name: Source ~/.bashrc to apply changes
  shell: source ~/.bashrc
  args:
    executable: /bin/bash